### ISSUE TITLE
Get new donor agreement

### ISSUE THREAD

**Issue by TBRC-JimK** [BuddhistDigitalResourceCenter/drs-deposit#23]
The first batch we process anywhere must contain a link to a donor agreement. This can be a mock agreement for QA, but must be the actual agreement for production. This issue could be satisfied simply by attaching a PDF/A version of the agreement to the issue.

**Comment by jeffwallman** [comment]
[Continuing Donor Agreement for Buddhist Digital Resource Cenre Digital Collection Project.pdf](https://github.com/BuddhistDigitalResourceCenter/drs-deposit/files/1623657/Continuing.Donor.Agreement.for.Buddhist.Digital.Resource.Cenre.Digital.Collection.Project.pdf)
