### ISSUE TITLE
METS export

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/drs-deposit#34]
following https://github.com/BuddhistDigitalResourceCenter/library-issues/issues/151 : @TBRC-JimK would it be possible to produce a big zip with all the METS data you're producing? I don't know the works you're working on, but W22084 would be very useful to start with...

**Comment by xristy** [comment]
indeed W22084 has Hollis Id 014258613 so it will be one of the works being generated.

**Comment by TBRC-JimK** [comment]
@TBRC-Travis , is there some way you could make Windhorse /Volumes/DRS_Staging shareable over its Ethernet? If so, I think @eroux could find a rich source of sample METS data in any batch's `batchWxxxxx/batchWxxxx-Iyyyy/descriptor.xml

**Comment by TBRC-JimK** [comment]
And please do shoot me a list of works you need this for (they will all share one HOLLIS id) and I can generate lots of batches.

**Comment by eroux** [comment]
I can access RS3, but I don't know if "Windhorse" and "RS3" are the same... are they? If I can't get the whole zip easily, I think we can start with W22084, it will be enough for me to produce the code, then we can run the code on the whole thing later, no need for it right now!

**Comment by eroux** [comment]
Well, thinking about it, it would probably be smarter to get the METS for more Kangyurs and Tengyurs, as that's a big part of what we'll show in the first demo. These would be W1PD96685, W22084, W22703, W1PD96684, W26071, W1PD96682, W1PD95844, W1GS66030, W1KG13126, W23703 and W22704

**Comment by xristy** [comment]
just checking for the `:workHollis` on each Work will indicate the Hollis ID if any. Then Jim should be able to locate the ones that have already been generated; generate if a Hollis ID is available; or faux generate and then bundle up the METS info. The batches include the images which of course are not wanted, but it might do well to let everyone know that just the METS records are needed.

**Comment by eroux** [comment]
ok, I have to say the DRS is a bit mysterious to me, but am I correct if I understand you're suggesting I make a list of hollisID instead of RID? I'll do that tomorrow if that's the case, no problem

**Comment by xristy** [comment]
The batch builder is driven with a list of RID, Hollis ID pairs. I simply indicating how to tell whether the Works of interest have a Hollis ID or not.

We can discuss the DRS in a chat.

**Comment by TBRC-JimK** [comment]
I should either have them built or may already have built them. I need about an hour to get to where I can check.

Jim Katz

**Comment by TBRC-JimK** [comment]
Elie, the works you have listed are all I need - no need to search for the Hollis.

**Comment by TBRC-Travis** [comment]
Sent Elie a first round of METS data <METS-descriptors-W22084-22703-22704.zip>

**Comment by eroux** [comment]
well received thanks!

**Comment by TBRC-JimK** [comment]
Hi, I'm building these batches now, should be done by noon latest.
﻿W1PD96685,14257985
W1PD96684,14257984
W26071,14259506
W1PD96682,14257983
W1PD95844,14257975
W1GS66030,14255521
W1KG13126,14256023
W23703,14259049

**Comment by TBRC-JimK** [comment]
An automated version of this is deployed since July 17. As `make-drs-batch.sh` builds batches, if the batch succeeds, the script calls tojsondimensions.py
