### ISSUE TITLE
Missing or out of sequence file

### ISSUE THREAD

**Issue by TBRC-JimK** [BuddhistDigitalResourceCenter/drs-deposit#38]
The missing 1079 file breaks the batch builder. Either the file needs to be located, or the files in the directory resequenced.
'''
/Volumes/WebArchive/W1PD95844/images/W1PD95844-I1PD95952/I1PD959521076.jpg
/Volumes/WebArchive/W1PD95844/images/W1PD95844-I1PD95952/I1PD959521077.jpg
/Volumes/WebArchive/W1PD95844/images/W1PD95844-I1PD95952/I1PD959521078.jpg
/Volumes/WebArchive/W1PD95844/images/W1PD95844-I1PD95952/I1PD959521080.jpg
/Volumes/WebArchive/W1PD95844/images/W1PD95844-I1PD95952/I1PD959521081.jpg
'''

**Comment by eroux** [comment]
There are a bunch of these, some even have very strange names, see last comment of https://github.com/BuddhistDigitalResourceCenter/library-issues/issues/28

**Comment by TBRC-JimK** [comment]
#60
