### ISSUE TITLE
Build HOLLIS lists

### ISSUE THREAD

**Issue by TBRC-JimK** [BuddhistDigitalResourceCenter/drs-deposit#9]
We have some sample lists of Works + HOLLIS ids as text files. Where do the rest of the HOLLIS ids come from? Shouls we store them in database?

**Comment by jeffwallman** [comment]
We request HOLLIS IDs from Harvard library folks. Once we get a batch, we update our database with HOLLIS IDs for each work.  So yes, they are in the database.

**Comment by TBRC-JimK** [comment]
See prior comment. All we need to do is to get them from the db
